# Generated by Django 2.2.12 on 2020-12-19 23:27

import addons.trixie_pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField()),
                ('content', addons.trixie_pages.models.TrixieField(blank=True)),
                ('template', models.CharField(blank=True, max_length=50)),
                ('edit_lock', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator_username', models.CharField(max_length=50, null=True)),
                ('owner_username', models.CharField(max_length=50, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_creator', to=settings.AUTH_USER_MODEL)),
                ('editing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_edit_lock', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trixie_pages.BasePage')),
            ],
            bases=('trixie_pages.basepage',),
        ),
    ]
