# Generated by Django 2.2.12 on 2021-01-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trixie_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basepage',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
