# Generated by Django 3.1.7 on 2021-02-28 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trixie_pages', '0002_auto_20210114_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='edit_lock',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basepage',
            name='editing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_edit_lock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basepage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
